/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#004965',
        'surface-tint': '#7bd0ff',
        'inverse-on-surface': '#283044',
        'tertiary-container': '#e1a800',
        primary: '#8ed5ff',
        'on-primary': '#00354a',
        'primary-container': '#38bdf8',
        secondary: '#4de082',
        'on-secondary': '#003919',
        'secondary-container': '#00b55d',
        'on-secondary-container': '#003e1c',
        'secondary-fixed-dim': '#4de082',
        'secondary-fixed': '#6dfe9c',
        tertiary: '#ffc42f',
        'on-tertiary': '#402d00',
        'tertiary-container': '#e1a800',
        'on-tertiary-container': '#584000',
        'tertiary-fixed': '#ffdf9f',
        'tertiary-fixed-dim': '#f9bd22',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#7bd0ff',
        'on-primary-fixed': '#001e2c',
        'on-primary-fixed-variant': '#004c69',
        'on-secondary-fixed': '#00210c',
        'on-secondary-fixed-variant': '#005227',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5c4300',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#bdc8d1',
        'inverse-surface': '#dae2fd',
        'inverse-primary': '#00668a',
        outline: '#87929a',
        'outline-variant': '#3e484f',
        background: '#0b1326',
        'on-background': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'header-height': '56px',
        gutter: '16px',
        unit: '4px',
        'sidebar-width': '320px',
        margin: '24px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '12px', fontWeight: '600' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
